services:
  db:
    container_name: shortener-db
    image: mysql:8.0
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=url_shortener
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=1234
    networks:
      - shortener-net
    ports:
      - 3306:3306
    expose:
      - 3306
    restart: always
  app:
    build:
      context: .
    container_name: shortener-spring
    ports:
      - 8080:8080
    environment:
      - MYSQL_HOST=db
      - MYSQL_USERNAME=sa
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=url_shortener
      - MYSQL_PORT=3306
    networks:
      - shortener-net
    depends_on:
      - db

volumes:
  db-data:
networks:
  shortener-net:
    name: shortener-net