name: Docker Compose CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Start containers
      run: COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose up -d
      
    - name: Test
      run: docker run --network=shortener-net container:shortener-spring appropriate/curl -s --retry 10 --retry-connrefused http://localhost:8080/
      
    - name: Stop containers
      if: always()
      run: docker-compose down
